version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py 
    volumes:
      - .:/app

