version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: express_redis_postgres_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
